//ANOTAÇÕES SOBRE JAVASCRIPT E NAVEGADOR
/*
-----------------------------------------------------------------------------------------------------------------------
PROTOCOLOS: É A FORMA EM QUE COMPUTADORES SE COMUNICAM NA REDE.
HTTP: SERVE PARA QUE POSSAMOS SOLICITAR ARQUIVOS, IMAGENS, E ETC.(HYPER TEXT TRANSFER PROTOCOL)
SMTP: PROTOCOLOS PARA ENVIAR EMAIL.
TCP: PROTOCOLO DE TRANSFERÊNCIA.
-------------------------------------------------------------------------------------------------------------------------
URL: A URL (UNIFORM RESOURCE LOCATOR) É O CAMINNHO DO SITE E PODE SER DIVIDIDA EM 3 PARTES: PROTOCOLO, SERVIDOR E ARQUIVO.
-----------------------------------------------------------------------------------------------------------------------------
HTML: LINGUAGEM DE MARCAÇÃO.
AS TAGS DO HTML CRIAM TÍTULOS, PARÁGRAFOS, IMAGENS, LISTAS E ETC.
UMA TAG É DEFINIDA POR <P> </P>.
OBS: ALGUMAS TAGS NÃO POSSUEM FECHAMENTOS.

*ESTRUTURA DO HTML - > TODO DOCUMENTO HTML POSSUI DUAS PARTES IMPORTANTES , A "HEAD" E A "BODY". HEAD POSSUI TODA A PARTE DE CONFIGURAÇÃO, BODY TERÁ OS
ELEMENTOS VISUAIS, TUDO O QUE SE VÊ.
--------------------------------------------------------------------------------------------------------------------------
HTML E JAVASCRIPT - > UTILIZAMOS JAVASCRIPT EM HTML POR MEIO DA TAG "SCRIPT" ATRAVÉS DO SRC. ALGUMAS TAGS HTML ACEITAM EXECUÇÃO DE CÓDIGO JS DIRETO NO HTML
OBS: LEMBRANDO QUE SEMPRE QUE LINKAMOS UM ARQUIVO EXTERNO, ESTAMOS CHAMANDO O MESMO VIA PROTOCOLO HTTP.
OBS: VOCÊ PODE CHAMAR O ARQUIVO JS TANTO NO HEAD OU NO BODY, MAS É MAIS RECOMENDADO QUE SE CHAME DENTRO DO BODY, POIS É UMA GARANTIA QUE TODA CONFIGURAÇÃO
DENTRO DO HEAD SEJA EXECUTADA.

*/
